name = "CoreOptimized"
author = "SniperXJohn"
version = "1.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3e7dd88e09c1d35cff623413784723dd87e903dc15c0e96f5a5bfb35d1a533d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
