name = "CoreOptimized"
author = "SniperXJohn"
version = "1.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef1241683a7e327dd2e69ecb3400d9c1d13f4deb9ec763a5a724ba7b9398a760"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
