name = "CoreOptimized"
author = "SniperXJohn"
version = "1.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f627360f05a03a61cc1b62d4b3d067dcbab9ad1881e4e021160349e034074efe"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
