name = "CoreOptimized"
author = "SniperXJohn"
version = "11.2.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "792058a7eb252e167b7243a9cebfd533df11cac54ee65fff681db054068ea05f"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"
