name = "CoreOptimized"
author = "SniperXJohn"
version = "11.2.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13565642a437f23a0917646468bc8803480b8d118e8322a3cb4882116f2a979"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
