name = "CoreOptimized"
author = "SniperXJohn"
version = "11.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "218b6db9b3303601b42bb43112cf5503ca5c7e439b75ed03d9a3a13c39f8ac53"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
