name = "CoreOptimized"
author = "SniperXJohn"
version = "12.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79abdac55556afd9c8e08a96e9024d7ed51c12b40c946dbf18feaea68450e48f"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
