name = "CoreOptimized"
author = "SniperXJohn"
version = "12.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d789198e861bda731073cea02e76ca0981d5068903674eca6e753aba55f1f92e"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
