name = "CoreOptimized"
author = "SniperXJohn"
version = "12.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ac5ec6b528de84a63bc41016240dd0a52f9a73f4aef1cf035aed41faec0391e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
