name = "CoreOptimized"
author = "SniperXJohn"
version = "11.1.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4049e2d162025da7fa025553b5b0d376e1c444bbdece70dc1e7ac4cf2a080204"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
