name = "CoreOptimized"
author = "SniperXJohn"
version = "13.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd70b803824dc435816c26272e5c5bd520e08de14ed01577eee81b66e7c2371"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
